<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'judul' => 'Laravel untuk Pemula',
                'penulis' => 'Dian Prasetyo',
                'penerbit' => 'Informatika Press',
                'tahun_terbit' => 2022,
                'isbn' => '9781234567890',
                'jumlah_halaman' => 210,
                'harga' => 75000,
                'stok' => 10,
                'kategori_id' => 1,
                'diskon_id' => 2,
                'deskripsi' => 'Panduan dasar untuk memulai belajar Laravel.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Mastering PHP 8',
                'penulis' => 'Rina Sari',
                'penerbit' => 'CodeHouse',
                'tahun_terbit' => 2023,
                'isbn' => '9780987654321',
                'jumlah_halaman' => 320,
                'harga' => 95000,
                'stok' => 5,
                'kategori_id' => 2,
                'diskon_id' => 1,
                'deskripsi' => 'Buku lanjutan untuk menguasai PHP versi terbaru.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Membangun REST API',
                'penulis' => 'Arif Hidayat',
                'penerbit' => 'DevBooks',
                'tahun_terbit' => 2021,
                'isbn' => '9781112223334',
                'jumlah_halaman' => 180,
                'harga' => 68000,
                'stok' => 12,
                'kategori_id' => 1,
                'diskon_id' => null,
                'deskripsi' => 'Langkah demi langkah membangun RESTful API dengan Laravel.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Desain Database Modern',
                'penulis' => 'Yusuf Akbar',
                'penerbit' => 'SQLindo',
                'tahun_terbit' => 2020,
                'isbn' => '9782223334445',
                'jumlah_halaman' => 250,
                'harga' => 85000,
                'stok' => 8,
                'kategori_id' => 3,
                'diskon_id' => 1,
                'deskripsi' => 'Dasar hingga mahir dalam merancang skema database relasional.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Logika Algoritma dan Pemrograman',
                'penulis' => 'Budi Santosa',
                'penerbit' => 'Teknika Media',
                'tahun_terbit' => 2019,
                'isbn' => '9783334445556',
                'jumlah_halaman' => 300,
                'harga' => 79000,
                'stok' => 7,
                'kategori_id' => 2,
                'diskon_id' => 3,
                'deskripsi' => 'Materi logika dasar dan pemrograman dengan studi kasus praktis.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Mastering PHP 8',
                'penulis' => 'Budi Santoso',
                'penerbit' => 'Graha Ilmu',
                'tahun_terbit' => 2021,
                'isbn' => '9781234567891',
                'jumlah_halaman' => 320,
                'harga' => 89000,
                'stok' => 12,
                'kategori_id' => 1,
                'diskon_id' => 1,
                'deskripsi' => 'Buku lengkap membahas fitur-fitur terbaru PHP 8.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Desain UI/UX Modern',
                'penulis' => 'Ratna Sari',
                'penerbit' => 'TeknoMedia',
                'tahun_terbit' => 2023,
                'isbn' => '9781234567892',
                'jumlah_halaman' => 198,
                'harga' => 68000,
                'stok' => 8,
                'kategori_id' => 3,
                'diskon_id' => 3,
                'deskripsi' => 'Pelajari prinsip dan praktik desain antarmuka pengguna modern.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Membangun REST API dengan Node.js',
                'penulis' => 'Yusuf Ramadhan',
                'penerbit' => 'Informatika Press',
                'tahun_terbit' => 2020,
                'isbn' => '9781234567893',
                'jumlah_halaman' => 260,
                'harga' => 82000,
                'stok' => 15,
                'kategori_id' => 2,
                'diskon_id' => 2,
                'deskripsi' => 'Panduan praktis membuat REST API menggunakan Node.js dan Express.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dasar-dasar Data Science',
                'penulis' => 'Anita Lestari',
                'penerbit' => 'DataBooks',
                'tahun_terbit' => 2021,
                'isbn' => '9781234567894',
                'jumlah_halaman' => 290,
                'harga' => 97000,
                'stok' => 7,
                'kategori_id' => 4,
                'diskon_id' => 2,
                'deskripsi' => 'Pengenalan dunia data science untuk pemula dengan studi kasus nyata.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Belajar Algoritma dan Struktur Data',
                'penulis' => 'Hendri Gunawan',
                'penerbit' => 'LogicPress',
                'tahun_terbit' => 2022,
                'isbn' => '9781234567895',
                'jumlah_halaman' => 350,
                'harga' => 105000,
                'stok' => 20,
                'kategori_id' => 1,
                'diskon_id' => 2,
                'deskripsi' => 'Teori dan implementasi algoritma serta struktur data menggunakan C++ dan Java.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Pengembangan Aplikasi Mobile dengan Flutter',
                'penulis' => 'Siti Aminah',
                'penerbit' => 'MobileTech',
                'tahun_terbit' => 2023,
                'isbn' => '9781234567896',
                'jumlah_halaman' => 280,
                'harga' => 89000,
                'stok' => 10,
                'kategori_id' => 4,
                'diskon_id' => 2,
                'deskripsi' => 'Panduan lengkap untuk membangun aplikasi mobile cross-platform menggunakan Flutter.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Web Development dengan React',
                'penulis' => 'Dewi Lestari',
                'penerbit' => 'WebTech',
                'tahun_terbit' => 2022,
                'isbn' => '9781234567897',
                'jumlah_halaman' => 300,
                'harga' => 92000,
                'stok' => 6,
                'kategori_id' => 2,
                'diskon_id' => 2,
                'deskripsi' => 'Membangun aplikasi web modern menggunakan React.js.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Pengantar Machine Learning',
                'penulis' => 'Fajar Prabowo',
                'penerbit' => 'AI Press',
                'tahun_terbit' => 2021,
                'isbn' => '9781234567898',
                'jumlah_halaman' => 400,
                'harga' => 120000,
                'stok' => 5,
                'kategori_id' => 4,
                'diskon_id' => 2,
                'deskripsi' => 'Dasar-dasar machine learning dengan Python dan scikit-learn.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Keamanan Siber untuk Pemula',
                'penulis' => 'Rudi Hartono',
                'penerbit' => 'CyberTech',
                'tahun_terbit' => 2023,
                'isbn' => '9781234567899',
                'jumlah_halaman' => 220,
                'harga' => 78000,
                'stok' => 9,
                'kategori_id' => 3,
                'diskon_id' => 2,
                'deskripsi' => 'Pengenalan konsep dasar keamanan siber dan praktik terbaik.',
                'gambar' => 'gambar/no-image.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
